server:
  port: 8282

# Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:electronics-store}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred


# Other Configuration
user:
  profile:
    image:
      path: images/users/

category:
  image:
    path: images/category/

product:
  image:
    path: images/product/


application:
  security:
    jwt:
      secret_key: ${SECRET_KEY}
      expiration: 8640000
      private_key: classpath:certs/privateKey.pem
      public_key: classpath:certs/publicKey.pem
      passphrase: ${DECRYPT_PASS}
